### Data

In [54]:
import numpy as np
from random import randint
from sklearn.preprocessing import MinMaxScaler

import keras
from keras import backend as k
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy

from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt

In [55]:
train_lables = []
train_samples = []
for i in range(50):
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_lables.append(0)
    
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_lables.append(1)
    
for i in range(1000):
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_lables.append(1)
    
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_lables.append(0)

test_labels = []
test_samples = []

for i in range(10):
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(1)
    
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)
    
for i in range(200):
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(0)
    
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(1)
    
train_lables = np.array(train_lables)
train_samples = np.array(train_samples)

test_labels = np.array(test_labels)
test_samples = np.array(test_samples)

#Scaled the data
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform((train_samples).reshape(-1, 1))
scaled_test_samples = scaler.fit_transform((test_samples).reshape(-1, 1))

In [56]:
model = Sequential([
    Dense(16, input_shape=(1,), activation='relu'),
    Dense(32, activation = 'relu'),
    Dense(2, activation = 'softmax')
])
model.summary()

model.compile(Adam(lr = .0001), loss='sparse_categorical_crossentropy', 
                   metrics=['accuracy'])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_8 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_9 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [57]:
model.fit(scaled_train_samples, train_lables, 
          batch_size = 10, 
          epochs = 20,
          shuffle= True,
          verbose = 2)
#batch_size : how many sample

Epoch 1/20
 - 1s - loss: 0.6883 - acc: 0.6600
Epoch 2/20
 - 0s - loss: 0.6725 - acc: 0.7681
Epoch 3/20
 - 0s - loss: 0.6447 - acc: 0.8724
Epoch 4/20
 - 0s - loss: 0.6134 - acc: 0.8771
Epoch 5/20
 - 0s - loss: 0.5799 - acc: 0.8895
Epoch 6/20
 - 0s - loss: 0.5439 - acc: 0.8905
Epoch 7/20
 - 0s - loss: 0.5068 - acc: 0.8871
Epoch 8/20
 - 0s - loss: 0.4681 - acc: 0.8962
Epoch 9/20
 - 0s - loss: 0.4340 - acc: 0.9086
Epoch 10/20
 - 0s - loss: 0.4050 - acc: 0.9090
Epoch 11/20
 - 0s - loss: 0.3807 - acc: 0.9100
Epoch 12/20
 - 0s - loss: 0.3611 - acc: 0.9152
Epoch 13/20
 - 0s - loss: 0.3448 - acc: 0.9186
Epoch 14/20
 - 0s - loss: 0.3317 - acc: 0.9190
Epoch 15/20
 - 0s - loss: 0.3210 - acc: 0.9224
Epoch 16/20
 - 0s - loss: 0.3122 - acc: 0.9248
Epoch 17/20
 - 0s - loss: 0.3050 - acc: 0.9238
Epoch 18/20
 - 0s - loss: 0.2994 - acc: 0.9271
Epoch 19/20
 - 0s - loss: 0.2944 - acc: 0.9324
Epoch 20/20
 - 0s - loss: 0.2904 - acc: 0.9276


model---2

In [58]:
model.fit(scaled_train_samples, train_lables, 
          #validation_set..,
          validation_split = 0.1, #it take last 10% data
          batch_size = 10, 
          epochs = 20,
          shuffle= True,
          verbose = 2)
#batch_size : how many sample

Train on 1890 samples, validate on 210 samples
Epoch 1/20
 - 0s - loss: 0.3017 - acc: 0.9222 - val_loss: 0.1545 - val_acc: 0.9857
Epoch 2/20
 - 0s - loss: 0.2997 - acc: 0.9222 - val_loss: 0.1505 - val_acc: 0.9857
Epoch 3/20
 - 0s - loss: 0.2976 - acc: 0.9206 - val_loss: 0.1465 - val_acc: 0.9905
Epoch 4/20
 - 0s - loss: 0.2958 - acc: 0.9270 - val_loss: 0.1434 - val_acc: 0.9905
Epoch 5/20
 - 0s - loss: 0.2942 - acc: 0.9291 - val_loss: 0.1402 - val_acc: 0.9857
Epoch 6/20
 - 0s - loss: 0.2928 - acc: 0.9238 - val_loss: 0.1374 - val_acc: 0.9905
Epoch 7/20
 - 0s - loss: 0.2914 - acc: 0.9265 - val_loss: 0.1351 - val_acc: 0.9905
Epoch 8/20
 - 0s - loss: 0.2901 - acc: 0.9270 - val_loss: 0.1328 - val_acc: 0.9905
Epoch 9/20
 - 0s - loss: 0.2889 - acc: 0.9286 - val_loss: 0.1303 - val_acc: 0.9905
Epoch 10/20
 - 0s - loss: 0.2877 - acc: 0.9259 - val_loss: 0.1286 - val_acc: 0.9905
Epoch 11/20
 - 0s - loss: 0.2865 - acc: 0.9286 - val_loss: 0.1267 - val_acc: 0.9905
Epoch 12/20
 - 0s - loss: 0.2853 - acc

In [59]:
model.fit(scaled_train_samples, train_lables, 
          #validation_set..,
          validation_split = 0.1, #it take last 10% data
          batch_size = 10, 
          epochs = 20,
          shuffle= True,
          verbose = 2)
#batch_size : how many sample

Train on 1890 samples, validate on 210 samples
Epoch 1/20
 - 0s - loss: 0.2772 - acc: 0.9286 - val_loss: 0.1132 - val_acc: 0.9905
Epoch 2/20
 - 0s - loss: 0.2764 - acc: 0.9286 - val_loss: 0.1122 - val_acc: 0.9905
Epoch 3/20
 - 0s - loss: 0.2755 - acc: 0.9307 - val_loss: 0.1111 - val_acc: 0.9905
Epoch 4/20
 - 0s - loss: 0.2748 - acc: 0.9286 - val_loss: 0.1101 - val_acc: 0.9905
Epoch 5/20
 - 0s - loss: 0.2741 - acc: 0.9302 - val_loss: 0.1095 - val_acc: 0.9905
Epoch 6/20
 - 0s - loss: 0.2733 - acc: 0.9302 - val_loss: 0.1083 - val_acc: 0.9905
Epoch 7/20
 - 0s - loss: 0.2726 - acc: 0.9317 - val_loss: 0.1076 - val_acc: 1.0000
Epoch 8/20
 - 0s - loss: 0.2720 - acc: 0.9333 - val_loss: 0.1065 - val_acc: 0.9905
Epoch 9/20
 - 0s - loss: 0.2713 - acc: 0.9296 - val_loss: 0.1057 - val_acc: 1.0000
Epoch 10/20
 - 0s - loss: 0.2708 - acc: 0.9323 - val_loss: 0.1052 - val_acc: 1.0000
Epoch 11/20
 - 0s - loss: 0.2701 - acc: 0.9354 - val_loss: 0.1045 - val_acc: 0.9905
Epoch 12/20
 - 0s - loss: 0.2696 - acc

### Predict

In [60]:
predictions = model.predict(scaled_test_samples , batch_size = 10, verbose = 0)
#top 2 rows
predictions[:2]

array([[0.38884413, 0.61115587],
       [0.9061343 , 0.09386574]], dtype=float32)

In [61]:
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose = 0)
rounded_predictions[:3]

array([1, 0, 1])

Confusion Matrix

In [62]:
cm = confusion_matrix(test_labels, rounded_predictions)
cm

array([[ 17, 193],
       [200,  10]])

Save and Load Model

In [63]:
model.save('medicle_trial_model.h5')

In [64]:
from keras.models import load_model
new_model = load_model('medicle_trial_model.h5')
new_model.summary()
new_model.get_weights()
new_model.optimizer

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_8 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_9 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


Model.to_json
only store architecture

In [65]:
json_str = model.to_json()
json_str

'{"class_name": "Sequential", "config": {"name": "sequential_3", "layers": [{"class_name": "Dense", "config": {"name": "dense_7", "trainable": true, "batch_input_shape": [null, 1], "dtype": "float32", "units": 16, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_8", "trainable": true, "units": 32, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": 

In [66]:
from keras.models import model_from_json
model_architecture = model_from_json(json_str)
model_architecture.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_8 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_9 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


model.save_weights()
It will save weights of models

In [67]:
model.save_weights('my_model_weights.h5')
model.summary

<bound method Network.summary of <keras.engine.sequential.Sequential object at 0x7f4e9c17fac8>>